version: "3.7"

services:

<<<<<<< HEAD
  back_end:
    build: ./Back-End
    depends_on:
      - messaging
    environment:
      AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
=======
  #front_end:
    #build: ./Front-End
    #ports:
      #- 5000:80
>>>>>>> upstream/master

  messaging:
    build: ./Messaging
    ports:
      - 5672:5672 # Default port for RabbitMQ message broker
      - 15672:15672 # Default port for RabbitMQ GUI

  back_end:
    build: ./Back-End
    depends_on:
      - database
      - messaging
    volumes:
     - "./Back-End:/usr/src/myapp"
  database:
    build: ./Database-1
    volumes:
      - "./Database-1/db:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
