# Author: Freddy Roa-Familia
# Version: 1.0
version: '3'
services:
 mariadb: 
  image: 'mariadb'
  environment:
   MYSQL_ROOT_PASSWORD: secret-pw
   # Sets the default password 
 messaging:
  image: 'rabbitmq:3-management'
