# Author: Freddy Roa-Familia
# Version: 1.1
version: "3.7"
services:
 
  back_end:
    build: ./Back-End
    depends_on:
      - messaging
    environment:
      AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'

  messaging:
    image: rabbitmq:3.8.2-management-alpine
    ports:
      - '5672:5672'   # Default port for RabbitMQ message broker
      - '15672:15672' # Default port for RabbitMQ GUI

  front_end:
   build: ./Front-End # Needs editing
   ports:
    - "5000:80"

  database:
<<<<<<< HEAD
    image: mysql:latest
    build: ./Database-1
    volumes:
      - "./Database-1/db:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
=======
   image: mysql:latest
   build: ./Database-1
   ports:
    -3306:3306
>>>>>>> c568e65afe36bcaec1c7246632c3e069cf8b708d
